[package]
org = "ballerinax"
name = "awslambda"
version = "2.2.1"
distribution = "2201.4.0"
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.lambda"
license = ["Apache-2.0"]
keywords = ["aws", "lambda", "serverless", "cloud"]
